title: Lokalise APIv2 Ruby SDK
email: bodrovis@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ruby interface for the Lokalise APIv2 that
  represents returned data as Ruby objects.
baseurl: "/ruby-lokalise-api" # the subpath of your site, e.g. /blog
url: "https://lokalise.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lokalise
github_username:  lokalise

# Build settings
markdown: kramdown
theme: null

strict_front_matter: true

plugins:
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-sitemap

jekyll-minifier:
  remove_intertag_spaces: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"